import { CreateBookDto } from './dto/create-book.dto';

export const BOOKS_SEED_DATA: ReadonlyArray<CreateBookDto> = [
  {
    title: 'Clean Code',
    author: 'Robert C. Martin',
    year: 2008,
    genre: 'Software',
    isbn: '9780132350884',
    price: 34.9,
    url: 'https://example.com/books/clean-code',
  },
  {
    title: 'The Pragmatic Programmer',
    author: 'Andrew Hunt',
    year: 1999,
    genre: 'Software',
    isbn: '9780201616224',
    price: 29.9,
    url: 'https://example.com/books/the-pragmatic-programmer',
  },
  {
    title: 'Cien anos de soledad',
    author: 'Gabriel Garcia Marquez',
    year: 1967,
    genre: 'Realismo magico',
    isbn: '9780307474728',
    price: 19.99,
    url: 'https://example.com/books/cien-anos-de-soledad',
  },
  {
    title: 'Refactoring',
    author: 'Martin Fowler',
    year: 1999,
    genre: 'Software',
    isbn: '9780201485677',
    price: 37.5,
    url: 'https://example.com/books/refactoring',
  },
  {
    title: 'Design Patterns',
    author: 'Erich Gamma',
    year: 1994,
    genre: 'Software',
    isbn: '9780201633610',
    price: 41.9,
    url: 'https://example.com/books/design-patterns',
  },
  {
    title: 'Domain-Driven Design',
    author: 'Eric Evans',
    year: 2003,
    genre: 'Software',
    isbn: '9780321125217',
    price: 42.5,
    url: 'https://example.com/books/domain-driven-design',
  },
  {
    title: 'Patterns of Enterprise Application Architecture',
    author: 'Martin Fowler',
    year: 2002,
    genre: 'Software',
    isbn: '9780321127426',
    price: 44.9,
    url: 'https://example.com/books/patterns-of-enterprise-application-architecture',
  },
  {
    title: 'Working Effectively with Legacy Code',
    author: 'Michael Feathers',
    year: 2004,
    genre: 'Software',
    isbn: '9780131177055',
    price: 38.4,
    url: 'https://example.com/books/working-effectively-with-legacy-code',
  },
  {
    title: 'You Do Not Know JS Yet',
    author: 'Kyle Simpson',
    year: 2020,
    genre: 'Software',
    isbn: '9781091210097',
    price: 24.99,
    url: 'https://example.com/books/you-do-not-know-js-yet',
  },
  {
    title: 'The Mythical Man-Month',
    author: 'Frederick P. Brooks Jr.',
    year: 1975,
    genre: 'Software',
    isbn: '9780201835953',
    price: 21.5,
    url: 'https://example.com/books/the-mythical-man-month',
  },
  {
    title: 'The Phoenix Project',
    author: 'Gene Kim',
    year: 2013,
    genre: 'DevOps',
    isbn: '9780988262591',
    price: 26.75,
    url: 'https://example.com/books/the-phoenix-project',
  },
  {
    title: 'Accelerate',
    author: 'Nicole Forsgren',
    year: 2018,
    genre: 'DevOps',
    isbn: '9781942788331',
    price: 27.6,
    url: 'https://example.com/books/accelerate',
  },
  {
    title: 'Deep Work',
    author: 'Cal Newport',
    year: 2016,
    genre: 'Productivity',
    isbn: '9781455586691',
    price: 18.9,
    url: 'https://example.com/books/deep-work',
  },
  {
    title: 'Atomic Habits',
    author: 'James Clear',
    year: 2018,
    genre: 'Productivity',
    isbn: '9780735211292',
    price: 17.5,
    url: 'https://example.com/books/atomic-habits',
  },
  {
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    year: 2011,
    genre: 'History',
    isbn: '9780062316097',
    price: 23.4,
    url: 'https://example.com/books/sapiens',
  },
  {
    title: 'Educated',
    author: 'Tara Westover',
    year: 2018,
    genre: 'Memoir',
    isbn: '9780399590504',
    price: 16.9,
    url: 'https://example.com/books/educated',
  },
  {
    title: 'The Hobbit',
    author: 'J. R. R. Tolkien',
    year: 1937,
    genre: 'Fantasy',
    isbn: '9780547928227',
    price: 14.25,
    url: 'https://example.com/books/the-hobbit',
  },
  {
    title: 'Dune',
    author: 'Frank Herbert',
    year: 1965,
    genre: 'Science Fiction',
    isbn: '9780441172719',
    price: 15.75,
    url: 'https://example.com/books/dune',
  },
  {
    title: 'Neuromancer',
    author: 'William Gibson',
    year: 1984,
    genre: 'Science Fiction',
    isbn: '9780441569595',
    price: 13.8,
    url: 'https://example.com/books/neuromancer',
  },
  {
    title: 'The Left Hand of Darkness',
    author: 'Ursula K. Le Guin',
    year: 1969,
    genre: 'Science Fiction',
    isbn: '9780441478125',
    price: 14.6,
    url: 'https://example.com/books/the-left-hand-of-darkness',
  },
  {
    title: 'The Name of the Wind',
    author: 'Patrick Rothfuss',
    year: 2007,
    genre: 'Fantasy',
    isbn: '9780756404741',
    price: 19.2,
    url: 'https://example.com/books/the-name-of-the-wind',
  },
  {
    title: '1984',
    author: 'George Orwell',
    year: 1949,
    genre: 'Dystopian',
    isbn: '9780451524935',
    price: 12.4,
    url: 'https://example.com/books/1984',
  },
  {
    title: 'Brave New World',
    author: 'Aldous Huxley',
    year: 1932,
    genre: 'Dystopian',
    isbn: '9780060850524',
    price: 13.1,
    url: 'https://example.com/books/brave-new-world',
  },
  {
    title: 'The Martian',
    author: 'Andy Weir',
    year: 2011,
    genre: 'Science Fiction',
    isbn: '9780553418026',
    price: 16.2,
    url: 'https://example.com/books/the-martian',
  },
  {
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    year: 2021,
    genre: 'Science Fiction',
    isbn: '9780593135204',
    price: 22.0,
    url: 'https://example.com/books/project-hail-mary',
  },
  {
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    year: 1960,
    genre: 'Classic',
    isbn: '9780061120084',
    price: 11.9,
    url: 'https://example.com/books/to-kill-a-mockingbird',
  },
  {
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    year: 1813,
    genre: 'Classic',
    isbn: '9780141439518',
    price: 10.5,
    url: 'https://example.com/books/pride-and-prejudice',
  },
  {
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    year: 1988,
    genre: 'Fiction',
    isbn: '9780061122415',
    price: 12.75,
    url: 'https://example.com/books/the-alchemist',
  },
  {
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    year: 2011,
    genre: 'Psychology',
    isbn: '9780374533557',
    price: 18.3,
    url: 'https://example.com/books/thinking-fast-and-slow',
  },
  {
    title: 'Hooked',
    author: 'Nir Eyal',
    year: 2014,
    genre: 'Product',
    isbn: '9781591847786',
    price: 20.4,
    url: 'https://example.com/books/hooked',
  },
  {
    title: 'Inspired',
    author: 'Marty Cagan',
    year: 2017,
    genre: 'Product',
    isbn: '9781119387503',
    price: 28.8,
    url: 'https://example.com/books/inspired',
  },
];
